### ISSUE TITLE
How to install chrome browser?

### ISSUE THREAD

**Issue by cayden** [scottyhardy/docker-remote-desktop#11]
how to install chrome browser in the ubuntu, thank you!

**Comment by scottyhardy** [comment]
I vaguely remember testing out installing chrome vs chromium vs firefox a while back and I think the problem was that chrome based installs were using snaps instead of .deb and refused to work and I haven't returned to it since.  I don't want to include multiple browsers so it's not something I'm going to spend time on, but if you want to investigate and submit a pull request that includes it and it builds ok then I'd likely just add it.

**Comment by develmac** [comment]
You can use this guide to install Chrome: https://ubuntuhandbook.org/index.php/2020/06/install-chromium-via-deb-ubuntu-20-04/
I guess it could be done in the Dockerfile. 
Sadly playing videos in Chrome does not work yet (I would need it for the Synology Surveillance Station).
