### ISSUE TITLE
add browser and git

### ISSUE THREAD

**Issue by mhmh55516** [scottyhardy/docker-remote-desktop#3]
Hi can you add firefox browser ?!
Thank you

**Comment by scottyhardy** [comment]
I ended up going with Firefox as it's the most common browser for Linux and Chromium is provided by `snapd` package manager which I couldn't get to work.  I'm not including Flash plugin due to it nearing end of support.

I'll need to update the `docker-wine` script to include `--shm-size="1g"` to the `docker run` command, otherwise Firefox tabs continually keep crashing.  I'll get that updated once I've pushed out the updated images.

**Comment by mhmh55516** [comment]
you can run Chromium with this command "chromium --no-sandbox"

**Comment by scottyhardy** [comment]
The issue was when trying to install chromium during a build it kept failing to contact the snap server. I originally used `apt-get install` and also tried installing snapd and using `snap install` but both methods failed so I stopped there.

**Comment by scottyhardy** [comment]
Hi @mhmh55516 

This issue's been resolved now and I've tested to ensure the downstream docker-wine image includes Firefox and git.  Thanks for the feedback and suggestions 😄
